=== imperialCHEPI/healthgps/schemas/v1/config/models/kevinhall.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/imperialCHEPI/healthgps/main/schemas/v1/config/models/kevinhall.json",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "ModelName": {
            "const": "KevinHall"
        },
        "Nutrients": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "Name": {
                        "type": "string"
                    },
                    "Range": {
                        "type": "array",
                        "items": {
                            "type": "number",
                            "minimum": 0.0
                        },
                        "minItems": 2,
                        "maxItems": 2
                    },
                    "Energy": {
                        "type": "number",
                        "minimum": 0.0
                    }
                },
                "additionalProperties": false
            },
            "minItems": 1
        },
        "Foods": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "Name": {
                        "type": "string"
                    },
                    "Nutrients": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "number"
                        }
                    },
                    "Price": {
                        "anyOf": [
                            {
                                "type": "number"
                            },
                            {
                                "type": "null"
                            }
                        ]
                    }
                },
                "additionalProperties": false
            }
        },
        "WeightQuantiles": {
            "propertyNames": {
                "enum": [
                    "Male",
                    "Female"
                ]
            },
            "additionalProperties": {
                "$ref": "../csv_file.json"
            }
        },
        "EnergyPhysicalActivityQuantiles": {
            "$ref": "../csv_file.json"
        },
        "HeightStdDev": {
            "type": "object",
            "properties": {
                "Male": {
                    "type": "number"
                },
                "Female": {
                    "type": "number"
                }
            },
            "additionalProperties": false
        },
        "HeightSlope": {
            "type": "object",
            "properties": {
                "Male": {
                    "type": "number"
                },
                "Female": {
                    "type": "number"
                }
            },
            "additionalProperties": false
        },
        "Height": {
            "type": "object",
            "propertyNames": {
                "enum": [
                    "Male",
                    "Female"
                ]
            },
            "additionalProperties": {
                "$ref": "../csv_file.json"
            }
        }
    },
    "anyOf": [
        {
            "required": [
                "HeightStdDev",
                "HeightSlope"
            ]
        },
        {
            "required": [
                "Height"
            ]
        }
    ],
    "additionalProperties": false
}

=== imperialCHEPI/healthgps/example_new/KevinHall.json
{
    "ModelName": "KevinHall",
    "Nutrients": [
        {
            "Name": "Carbohydrate",
            "Range": [0.0, 50.0],
            "Energy": 4.0
        },
        {
            "Name": "Fat",
            "Range": [0.0, 50.0],
            "Energy": 9.0
        },
        {
            "Name": "Protein",
            "Range": [0.0, 50.0],
            "Energy": 4.0
        },
        {
            "Name": "Sodium",
            "Range": [0.0, 50.0],
            "Energy": 0.0
        }
    ],
    "Foods": [
        {
            "Name": "FoodCarbohydrate",
            "Nutrients": {
                "Carbohydrate": 1.0
            },
            "Price": null
        },
        {
            "Name": "FoodFat",
            "Nutrients": {
                "Fat": 1.0
            },
            "Price": null
        },
        {
            "Name": "FoodProtein",
            "Nutrients": {
                "Protein": 1.0
            },
            "Price": null
        },
        {
            "Name": "FoodSodium",
            "Nutrients": {
                "Sodium": 1.0
            },
            "Price": null
        }
    ],
    "WeightQuantiles": {
        "Female": {
            "name": "weight_quantiles_NCDRisk_female.csv",
            "format": "csv",
            "delimiter": ",",
            "encoding": "UTF8",
            "columns": {
                "quantile": "double"
            }
        },
        "Male": {
            "name": "weight_quantiles_NCDRisk_male.csv",
            "format": "csv",
            "delimiter": ",",
            "encoding": "UTF8",
            "columns": {
                "quantile": "double"
            }
        }
    },
    "EnergyPhysicalActivityQuantiles": {
        "name": "energy_physicalactivity_quantiles.csv",
        "format": "csv",
        "delimiter": ",",
        "encoding": "UTF8",
        "columns": {
            "quantile": "double"
        }
    },
    "HeightStdDev": {
        "Female": 0.096,
        "Male": 0.085
    },
    "HeightSlope": {
        "Female": 0.3564,
        "Male": 0.3718
    }
}
