=== imperialCHEPI/healthgps/schemas/v2/config/models/kevinhall.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/imperialCHEPI/healthgps/main/schemas/v2/config/models/kevinhall.json",
    "$defs": {
        "weightQuantileGenderEntry": {
            "oneOf": [
                {
                    "$ref": "../../../v1/config/csv_file.json"
                },
                {
                    "type": "object",
                    "propertyNames": {
                        "pattern": "^Quintile[1-9][0-9]*$"
                    },
                    "additionalProperties": {
                        "$ref": "../../../v1/config/csv_file.json"
                    },
                    "minProperties": 1
                }
            ]
        }
    },
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "ModelName": {
            "const": "KevinHall"
        },
        "Nutrients": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "Name": {
                        "type": "string"
                    },
                    "Unit": {
                        "type": "string"
                    },
                    "Range": {
                        "type": "array",
                        "items": {
                            "type": "number",
                            "minimum": 0.0
                        },
                        "minItems": 2,
                        "maxItems": 2
                    },
                    "Energy": {
                        "type": "number",
                        "minimum": 0.0
                    }
                },
                "additionalProperties": false
            },
            "minItems": 1
        },
        "Foods": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "Name": {
                        "type": "string"
                    },
                    "Nutrients": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "number"
                        }
                    },
                    "Price": {
                        "anyOf": [
                            {
                                "type": "number"
                            },
                            {
                                "type": "null"
                            }
                        ]
                    },
                    "ExpectedTrend": {
                        "type": "number"
                    },
                    "TrendSteps": {
                        "type": "integer"
                    },
                    "ExpectedIncomeTrend": {
                        "type": "number"
                    },
                    "IncomeTrendSteps": {
                        "type": "integer"
                    },
                    "IncomeDecayFactor": {
                        "type": "number",
                        "description": "Exponential decay factor 'b' for income trend calculation"
                    }
                },
                "additionalProperties": false
            }
        },
        "WeightQuantiles": {
            "type": "object",
            "propertyNames": {
                "enum": [
                    "Male",
                    "Female"
                ]
            },
            "additionalProperties": {
                "$ref": "#/$defs/weightQuantileGenderEntry"
            }
        },
        "EnergyPhysicalActivityQuantiles": {
            "$ref": "../../../v1/config/csv_file.json"
        },
        "HeightStdDev": {
            "type": "object",
            "properties": {
                "Male": {
                    "type": "number"
                },
                "Female": {
                    "type": "number"
                }
            },
            "additionalProperties": false
        },
        "HeightSlope": {
            "type": "object",
            "properties": {
                "Male": {
                    "type": "number"
                },
                "Female": {
                    "type": "number"
                }
            },
            "additionalProperties": false
        },
        "Height": {
            "type": "object",
            "propertyNames": {
                "enum": [
                    "Male",
                    "Female"
                ]
            },
            "additionalProperties": {
                "$ref": "../../../v1/config/csv_file.json"
            }
        }
    },
    "required": [
        "ModelName",
        "Nutrients",
        "Foods",
        "WeightQuantiles",
        "EnergyPhysicalActivityQuantiles"
    ],
    "anyOf": [
        {
            "required": [
                "HeightStdDev",
                "HeightSlope"
            ]
        },
        {
            "required": [
                "Height"
            ]
        }
    ],
    "additionalProperties": false
}

=== imperialCHEPI/healthgps/dynamic_model.json
{
    "$schema": "https://raw.githubusercontent.com/imperialCHEPI/healthgps/main/schemas/v2/config/models/kevinhall.json",
    "ModelName": "KevinHall",
    "Nutrients": [
        {
            "Name": "Carbohydrate",
            "Range": [
                0.018864257,
                1781.290527
            ],
            "Energy": 4.0
        },
        {
            "Name": "Protein",
            "Range": [
                0.008585715,
                359.7049561
            ],
            "Energy": 4.0
        },
        {
            "Name": "Fat",
            "Range": [
                0.0,
                1232.129272
            ],
            "Energy": 9.0
        },
        {
            "Name": "Sodium",
            "Range": [
                0.000200005,
                16.34803581
            ],
            "Energy": 0.0
        },
        {
            "Name": "Alcohol",
            "Range": [
                0,
                306.9281311
            ],
            "Energy": 7.0
        },
        {
            "Name": "ProcessedMeat",
            "Range": [
                0.0,
                932.5
            ],
            "Energy": 0.0
        },
        {
            "Name": "RedMeat",
            "Range": [
                0.0,
                476.6325559
            ],
            "Energy": 0.0
        },
        {
            "Name": "Legume",
            "Range": [
                0.0,
                433.6983613
            ],
            "Energy": 0.0
        },
        {
            "Name": "Fruit",
            "Range": [
                0.0,
                1720.489525
            ],
            "Energy": 0.0
        },
        {
            "Name": "Vegetable",
            "Range": [
                0.0,
                2046.825704
            ],
            "Energy": 0.0
        },
        {
            "Name": "AddedSugar",
            "Range": [
                0,
                758.3163452
            ],
            "Energy": 4.0
        },
        {
            "Name": "TotalSugar",
            "Range": [
                0.019693965,
                819.5865479
            ],
            "Energy": 0.0
        },
        {
            "Name": "MonounsaturatedFat",
            "Range": [
                0.0,
                483.5317688
            ],
            "Energy": 0.0
        },
        {
            "Name": "PolyunsaturatedFattyAcid",
            "Range": [
                0.0,
                473.1528015
            ],
            "Energy": 0.0
        },
        {
            "Name": "SaturatedFat",
            "Range": [
                0.0,
                276.9013672
            ],
            "Energy": 0.0
        },
        {
            "Name": "Fibre",
            "Range": [
                0.0,
                189.5542603
            ],
            "Energy": 0.0
        }
    ],
    "Foods": [
        {
            "Name": "FoodCarbohydrate",
            "Nutrients": {
                "Carbohydrate": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        },
        {
            "Name": "FoodProtein",
            "Nutrients": {
                "Protein": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        },
        {
            "Name": "FoodFat",
            "Nutrients": {
                "Fat": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        },
        {
            "Name": "FoodSodium",
            "Nutrients": {
                "Sodium": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        },
        {
            "Name": "FoodAlcohol",
            "Nutrients": {
                "Alcohol": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        },
        {
            "Name": "FoodLegume",
            "Nutrients": {
                "Legume": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        },
        {
            "Name": "FoodVegetable",
            "Nutrients": {
                "Vegetable": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        },
        {
            "Name": "FoodFruit",
            "Nutrients": {
                "Fruit": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        },
        {
            "Name": "FoodProcessedMeat",
            "Nutrients": {
                "ProcessedMeat": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        },
        {
            "Name": "FoodRedMeat",
            "Nutrients": {
                "RedMeat": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        },
        {
            "Name": "FoodFibre",
            "Nutrients": {
                "Fibre": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        },
        {
            "Name": "FoodTotalSugar",
            "Nutrients": {
                "TotalSugar": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        },
        {
            "Name": "FoodAddedSugar",
            "Nutrients": {
                "AddedSugar": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        },
        {
            "Name": "FoodSaturatedFat",
            "Nutrients": {
                "SaturatedFat": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        },
        {
            "Name": "FoodPolyunsaturatedFattyAcid",
            "Nutrients": {
                "PolyunsaturatedFattyAcid": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        },
        {
            "Name": "FoodMonounsaturatedFat",
            "Nutrients": {
                "MonounsaturatedFat": 1.0
            },
            "Price": null,
            "ExpectedTrend": 1.0,
            "TrendSteps": 0
        }
    ],
    "WeightQuantiles": {
        "Female": {
            "name": "weight_quantiles_NCDRisk_female.csv",
            "format": "csv",
            "delimiter": ",",
            "encoding": "ASCII",
            "columns": {
                "quantile": "double"
            }
        },
        "Male": {
            "name": "weight_quantiles_NCDRisk_male.csv",
            "format": "csv",
            "delimiter": ",",
            "encoding": "ASCII",
            "columns": {
                "quantile": "double"
            }
        }
    },
    "EnergyPhysicalActivityQuantiles": {
        "name": "energy_physicalactivity_quantiles.csv",
        "format": "csv",
        "delimiter": ",",
        "encoding": "ASCII",
        "columns": {
            "quantile": "double"
        }
    },
    "HeightStdDev": {
        "Female": 0.0628924471950273,
        "Male": 0.0567175327223389
    },
    "HeightSlope": {
        "Female": 0.224138825,
        "Male": 0.268517056586274
    }
}
